app: vscode
code.language: magit
-

magit status: user.vscode("magit.status")
magit dispatch: user.vscode("magit.dispatch")
magit file popup: user.vscode("magit.file-popup")

magit stage: user.vscode("magit.stage")
magit stage all: user.vscode("magit.stage-all")
magit unstage: user.vscode("magit.unstage")
magit unstage all: user.vscode("magit.unstage-all")

magit commit: user.vscode("magit.commit")
magit branch: user.vscode("magit.branching")
magit merge: user.vscode("magit.merging")
magit rebase: user.vscode("magit.rebasing")
magit reset: user.vscode("magit.resetting")
magit remote: user.vscode("magit.remoting")
magit log: user.vscode("magit.logging")
magit refs: user.vscode("magit.show-refs")
magit diff: user.vscode("magit.diffing")
magit tag: user.vscode("magit.tagging")
magit cherry pick: user.vscode("magit.cherry-picking")
magit revert: user.vscode("magit.reverting")
magit ignore: user.vscode("magit.ignoring")
magit run: user.vscode("magit.running")
magit worktree: user.vscode("magit.worktree")
magit push: user.vscode("magit.pushing")
magit pull: user.vscode("magit.pulling")
magit stash: user.vscode("magit.stashing")
magit submodule: user.vscode("magit.submodules")
magit fetch: user.vscode("magit.fetching")
magit process log: user.vscode("magit.process-log")
magit blame: user.vscode("magit.blame-file")
magit bisect: user.vscode("magit.bisect")

magit help: user.vscode("magit.help")
magit refresh: user.vscode("magit.refresh")
magit quit: user.vscode("magit.quit")
magit visit: user.vscode("magit.visit-at-point")
magit apply: user.vscode("magit.apply-at-point")
magit discard: user.vscode("magit.discard-at-point")
magit reverse: user.vscode("magit.reverse-at-point")
magit fold: user.vscode("magit.toggle-fold")
magit fold all: user.vscode("magit.toggle-all-folds-for-change-views")
magit fold section: user.vscode("magit.toggle-all-folds-in-change-section-at-point")
magit copy section: user.vscode("magit.copy-section-value")
magit copy revision: user.vscode("magit.copy-buffer-revision")
magit next: user.vscode("magit.move-next-entity")
magit previous: user.vscode("magit.move-previous-entity")
