whisper insert latest: user.whisper_insert_latest()
whisper history: user.whisper_history_toggle()
whisper history close: user.whisper_history_hide()
whisper history clear: user.whisper_history_clear()
whisper pick <number_small>: user.whisper_insert_history(number_small)
whisper polish session: user.whisper_polish_session()
whisper polished only: user.whisper_polished_only_set(true)
whisper polished fallback: user.whisper_polished_only_set(false)
whisper polished toggle: user.whisper_polished_only_toggle()
whisper polished status: user.whisper_polished_only_status()
whisper pending copy: user.whisper_pending_copy()
whisper session show: user.whisper_session_show()
whisper session insert: user.whisper_session_insert()
whisper context screen: user.whisper_context_capture()
whisper context show: user.whisper_context_show()
whisper context clear: user.whisper_context_clear()
whisper context selection:
    user.whisper_context_set(edit.selected_text())
whisper status: user.whisper_status()
whisper details: user.whisper_hud_details_toggle()
whisper test polish: user.whisper_test_polisher()
whisper test context: user.whisper_test_context()
whisper test all: user.whisper_test_all()
