# Onshape (browser) - Keyboard Shortcuts and Hotkeys
# Extracted from https://cad.onshape.com/help/Content/Home/keyboard_shortcuts_and_hotkeys.htm
#
# To use: Place this file in your Talon user directory under apps/onshape/onshape.talon
#
# Context: Onshape running in a browser (adjust context header as needed)

app: browser
window.title: /Onshape/
-
# --- General ---
shift+enter: user.onshape_commit_and_new_dialog()
enter: user.onshape_commit_command()
escape: user.onshape_exit_command()
space: user.onshape_deselect_features()
ctrl-c: user.onshape_copy_feature()
cmd-c: user.onshape_copy_feature()
shift-c: user.onshape_open_curve_surface_analysis()
delete: user.onshape_remove_selected_features()
backspace: user.onshape_remove_selected_features()
shift-d: user.onshape_dihedral_analysis()
ctrl-shift-f: user.onshape_featurescript_search()
cmd-shift-f: user.onshape_featurescript_search()
ctrl-u: user.onshape_feedback_bug()
a: user.onshape_flip_primary_axis()
k: user.onshape_toggle_mate_connectors()
shift-/: user.onshape_toggle_shortcuts_list()
shift: user.onshape_lock_mate_inference()
ctrl-m: user.onshape_open_mate_connector()
cmd-m: user.onshape_open_mate_connector()
[: user.onshape_open_measure_dialog()
ctrl-click: user.onshape_open_doc_new_tab()
cmd-click: user.onshape_open_doc_new_tab()
shift-click: user.onshape_open_doc_new_window()
ctrl-v: user.onshape_paste_feature()
cmd-v: user.onshape_paste_feature()
ctrl-space: user.onshape_switch_tabs()
cmd-space: user.onshape_switch_tabs()
ctrl-y: user.onshape_redo()
cmd-shift-z: user.onshape_redo()
shift-n: user.onshape_rename_instance()
q: user.onshape_construction_tool()
alt-c: user.onshape_search_tools()
option-c: user.onshape_search_tools()
` : user.onshape_entity_list()
s: user.onshape_shortcut_toolbar()
alt-t: user.onshape_tab_manager()
option-t: user.onshape_tab_manager()
ctrl-z: user.onshape_undo()
cmd-z: user.onshape_undo()

# --- Part Studio ---
shift-e: user.onshape_extrude()
shift-f: user.onshape_fillet()
shift-h: user.onshape_toggle_sketches()
shift-w: user.onshape_revolve()
shift-s: user.onshape_sketch()

# --- Assembly ---
j: user.onshape_toggle_mates()
i: user.onshape_insert_parts()
m: user.onshape_fasten_mate()
h: user.onshape_show_mates_mode()
shift-s: user.onshape_snap_mode()

# --- 3D View ---
shift-2: user.onshape_view_back()
shift-6: user.onshape_view_bottom()
shift-1: user.onshape_view_front()
shift-p: user.onshape_hide_construction_geometry()
y: user.onshape_hide_instance()
p: user.onshape_toggle_planes()
shift-7: user.onshape_view_isometric()
shift-3: user.onshape_view_left()
shift-i: user.onshape_isolate_instance()
shift-t: user.onshape_transparent_instance()
shift-v: user.onshape_named_views()
ctrl-shift-left: user.onshape_move_design_left()
ctrl-shift-right: user.onshape_move_design_right()
ctrl-shift-up: user.onshape_move_design_up()
ctrl-shift-down: user.onshape_move_design_down()
ctrl-left: user.onshape_rotate_design_left()
ctrl-right: user.onshape_rotate_design_right()
ctrl-up: user.onshape_rotate_design_up()
ctrl-down: user.onshape_rotate_design_down()
shift-left: user.onshape_rotate_design_90_left()
shift-right: user.onshape_rotate_design_90_right()
shift-up: user.onshape_rotate_design_90_up()
shift-down: user.onshape_rotate_design_90_down()
shift-4: user.onshape_view_right()
left: user.onshape_rotate_15_left()
right: user.onshape_rotate_15_right()
up: user.onshape_rotate_15_up()
down: user.onshape_rotate_15_down()
shift-x: user.onshape_section_view()
alt-click: user.onshape_select_through_transparent()
option-click: user.onshape_select_through_transparent()
shift-y: user.onshape_show_hidden_instance()
shift-5: user.onshape_view_top()
shift-r: user.onshape_view_high_quality()
n: user.onshape_reposition_parallel()
shift-z: user.onshape_zoom_center()
z: user.onshape_zoom_out()
f: user.onshape_fit_to_window()
w: user.onshape_zoom_box()

# --- Sketch ---
a: user.onshape_sketch_arc()
c: user.onshape_sketch_center_circle()
r: user.onshape_sketch_center_rectangle()
i: user.onshape_sketch_coincident()
shift-o: user.onshape_sketch_concentric()
g: user.onshape_sketch_corner_rectangle()
shift-u: user.onshape_sketch_curvature()
d: user.onshape_sketch_dimension()
e: user.onshape_sketch_equal()
x: user.onshape_sketch_extend()
shift-j: user.onshape_sketch_fix()
h: user.onshape_sketch_horizontal()
l: user.onshape_sketch_line()
shift-a: user.onshape_sketch_toggle_line_arc()
shift-m: user.onshape_sketch_midpoint()
shift-k: user.onshape_sketch_normal()
o: user.onshape_sketch_offset()
b: user.onshape_sketch_parallel()
shift-l: user.onshape_sketch_perpendicular()
shift-g: user.onshape_sketch_pierce()
shift-s: user.onshape_sketch_point()
shift-f: user.onshape_sketch_fillet()
shift: user.onshape_sketch_suppress_inference()
shift-q: user.onshape_sketch_symmetric()
t: user.onshape_sketch_tangent()
q: user.onshape_sketch_construction()
m: user.onshape_sketch_trim()
u: user.onshape_sketch_use()
v: user.onshape_sketch_vertical()

# --- Feature Studio ---
ctrl-s: user.onshape_commit_feature_studio()
cmd-s: user.onshape_commit_feature_studio()
ctrl-shift-s: user.onshape_commit_all_feature_studios()
cmd-shift-s: user.onshape_commit_all_feature_studios()
escape: user.onshape_dismiss_autocomplete()

# --- Drawings ---
alt-lmb-drag: user.onshape_copy_annotation_drag()
option-lmb-drag: user.onshape_copy_annotation_drag()
shift-d: user.onshape_diameter_dimension()
ctrl-s: user.onshape_toggle_sheets()
home: user.onshape_first_sheet()
end: user.onshape_last_sheet()
ctrl-m: user.onshape_max_min_dimension()
page-down: user.onshape_next_sheet()
n: user.onshape_note_tool()
page-up: user.onshape_prev_sheet()
p: user.onshape_projected_view()
shift-q: user.onshape_activate_midpoint_quad()
shift-r: user.onshape_radial_dimension()
ctrl-q: user.onshape_update_all_views()
