# Real-time VAD + Faster-Whisper Configuration

# Audio Settings
audio:
  sample_rate: 16000
  frame_duration_ms: 20
  
# VAD Settings
vad:
  aggressiveness: 2  # 0-3, higher = more aggressive
  start_gate_ms: 200  # Minimum speech duration to start transcription
  end_gate_ms: 400    # Minimum silence duration to end transcription
  padding_ms: 250     # Audio padding around speech segments

# Model Settings
model:
  size: "small"  # tiny, base, small, medium, large-v3
  device: "auto"  # auto, cuda, cpu
  compute_type: "auto"  # auto, float16, int8
  
# Transcription Settings
transcription:
  partial_interval_sec: 0.9  # How often to emit partial results
  partial_beam_size: 1       # Beam search for partial (fast)
  final_beam_size: 5         # Beam search for final (accurate)
  language: null             # Auto-detect or specify (en, es, fr, etc.)
  temperature: 0.0           # Randomness in generation
  condition_on_previous: false  # Use previous text as context

# Typing Settings
typing:
  backend: "auto"  # auto, xdotool, wtype, keyboard
  delay_ms: 0      # Delay between keystrokes
  use_clipboard: false  # Use clipboard instead of direct typing

# Performance Settings
performance:
  max_chunk_duration_sec: 30  # Maximum audio chunk length
  model_cache_size: 1        # Number of models to keep in memory
  
# Debug Settings
debug:
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_vad_activity: false
  log_transcription_time: true
  save_audio_chunks: false  # Save chunks to disk for debugging